### ISSUE TITLE
meaning of allow_other

### ISSUE THREAD

**Issue by pacifists** [latortuga/has_magic_columns#1]
Hello,

I've found this gem and it's working kind of perfectly (atleast for now and for what I'm doing). The thing I'm interested and can't yet seem to grasp what is the point of field 'allow_other' what it does allow or not allow ?

Also what are magic_options used for, cause I haven't yet found a way to add anything to them. I would gladly contribute tests to the project, but so far there's not enough info and understanding of the project so that I could write specs for it.

**Comment by latortuga** [comment]
Hey thanks for taking a look at the project! I managed to get the single model version working for the time being so the README is actually a little misleading but inherited models aren't working yet.

As to your inquiry about magic_options and the allow_other field, I actually found this code on Google Code so I couldn't tell you for sure what the field is for or really what the other tables are for yet because I'm sort of in the process of figuring it out. At present it "just works" so I'm going with what the original author designed.

**Comment by pacifists** [comment]
Hello, yes I'm doing exactly the same, just planning on adding `acts_as_list` for myself. You'll be able to pull it when it's done if you think this has place in the project. For me at the moment everything looks really good and after few hours of pulling my hair out it starts to make sense :) But for what I'm doing I'll need to order custom fields for the items so that's my main task for now.

Btw I've found by trial and error, that the examples could be easily improved, because if the `MagicColumn.name` matches existing one it can be reused. I've realized that after creating maybe 15 instances of the same name for the same record by the example :) it's just `@item.magic_attributes << MagicAttribute.new(:column => column_info, :value => 'user provided value')` to simply reused the existing column_info. Maybe this was already obvious for you, but not for me :)

Also I've noticed that it allows creation of column names that overlap with already existing columns of the model. This does not brake anything, but the field gets saved in 2 places :) In the original objects table and in magic columns table. That's not what I would like it to do, but the only fix I see for this now is to just check if it matches and if it does then:
a) show validation error to the user OR b) make the magic column name unique by adding something to it and save with new name instead. Maybe that's for the programmer to decide not the gem...

Thanks for good timing I'm just starting a project and needed this functionality and this is the only gem that's being worked at :) Have fun

**Comment by latortuga** [comment]
Thanks very much for the writeup and feedback, we'll definitely look into this and I look forward to the pull request!

**Comment by latortuga** [comment]
Re MagicAttributes, I'm not exactly sure I fully understand the problem you're describing. The interface to use is magic_columns.create and then to use them as though they were normal active record columns (e.g. user.magic_columns.create(:name => :salary) and then user.salary). There shouldn't be a need to use magic attributes as far as I can tell, unless you need it for ordering purposes. In that case I'll have to think more about it.

As for the duplicate field problem, I looked into it a bit and played around with trying to validate but I don't think it's really worthwhile. At the moment, the overridden ActiveRecord::Base#read_attribute will return the model attribute unconditionally if it exists so even if there is a collision, there shouldn't be any problem with it messing up your existing column names. It could definitely pose a headache if you were, for example, going to migrate from having a magic column to making it a normal column but for now I think I'm going to leave it as is. It's definitely an important issue to note so I'm going to include it in the README.

Lastly, to address your initial question, I believe `allow_other` is intended to be used in conjunction with magic_options. When setting up a magic_column, you can specify magic_options which would be values to show in e.g. a dropdown for the field. `allow_other` turns on and off the ability to set the value of a magic column to be something other than one of the magic_options. Think of it like `:allow_blank` in the normal rails `select` helper. Let me know if this clears up some confusion.

**Comment by pacifists** [comment]
Hello again,

There will be no pull request from me cause we've ditched mysql altogether and went for mongodb after struggling with custom fields and realizing that this will be needed much more often than we have thought. Have fun developing this gem it's really nice solution and it already works :)
